language: node_js
cache:
  directories:
    - ~/.npm
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn add react
  - yarn add --dev jest babel-jest babel-core enzyme enzyme-adapter-react-16
  - yarn add --dev react-test-renderer
script:
  - yarn run test
  - yarn run build
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
