language: node_js
cache:
  directories:
    - ~/.npm
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn add react --peer
script:
  - yarn test
  - yarn run build
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
